[package]
name = "credit"
version = "1.0.0"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"
description = "A tool for measuring Github repository contributions"
homepage = "https://github.com/fosskers/credit"
repository = "https://github.com/fosskers/credit"
readme = "README.md"
license = "MIT"
keywords = ["github"]
categories = ["command-line-utilities"]

[dependencies]
auto_from = "0.3"
chrono = { version = "0.4", features = ["serde"] }
isahc = { version = "0.9", features = ["json"] }
itertools = "0.9"
rayon = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
